version: '3.8'
services:
    pgsql:
        image: postgres
        container_name: newsletter
        user: root
        hostname: pgsql
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=newsletter
            - POSTGRES_USER=postgres
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=localhost
        ports:
            - '5432:5432'
        volumes:
            - './.docker/.postgres-data:/var/lib/postgresql/data'
    redis:
        image: redis:7
        container_name: redis_session
        ports:
            - '6379:6379'
